### ISSUE TITLE
In the data_loader.py Line#17 might cause some errors.

### ISSUE THREAD

**Issue by siaoliu** [Zerg-Overmind/QC-DGM#6]
https://github.com/Zerg-Overmind/QC-DGM/blob/970fcb4330aa2d7da6ebde4fdaf90e0151ac5f60/data/data_loader.py#L17

data_loader.py Line#17 def __init__(self, name, length, cls=None, **args):
"cls" is a default inner parameter like "max, min".
In python 3.7, there is a confusing problem:  **TypeError: __new__() got multiple values for argument 'cls'**
Just change the cls to another word in this .py file, e.g. following, could be fine.

`def __init__(self, name, length, cls_name=None, **args):
`
and Line#24 also should rename:

`self.cls = None if cls_name == 'none' else cls_name`

Sincerely thank the authors for the open source work.

**Comment by Zerg-Overmind** [comment]
Thanks a lot for pointing out !!
